/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.RoleBasedWorkAreas;

import Business.LoginPerson.LoginPerson;
import Business.Models.Crop;
import Business.Models.CropScheduleTechniqueRelation;
import Business.Roles.CropPlanner;
import UserInterface.RoleBasedWorkAreas.CropPlannerPanels.CPAnalyseForecastDemandJPanel;
import UserInterface.RoleBasedWorkAreas.CropPlannerPanels.CropPlantingScheduleJPanel;
import UserInterface.RoleBasedWorkAreas.DataAnalystPanels.DABestCropsJPanel;
import static Utils.Constants.roles;
import static Utils.HistoricalData.plannedCrops;
import java.awt.CardLayout;
import java.util.*;
import javax.swing.JPanel;

/**
 *
 * @author yash
 */
public class CropPlannerJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CropPlannerJPanel
     */
    // this should be passed from login into constructor
    CropPlanner loggedInCropPlanner;
    List<CropPlanner> cropPlannerList = new ArrayList<>();
    JPanel MainJPanel;

    
    CropPlanner cropPlanner;
    HashMap<Crop, List<CropScheduleTechniqueRelation>> scheduleOfAllCrops;
    ArrayList<String> cropPlannerScheduleList;
    LoginPerson person;
    ArrayList<Crop> selectedCrops;

    
    public CropPlannerJPanel(HashMap<Crop,List<CropScheduleTechniqueRelation>>scheduleOfAllCrops,LoginPerson person,List<CropPlanner> cropPlannerList,JPanel MainJPanel


) {
        initComponents();
        cropPlanner= new CropPlanner();
        this.MainJPanel = MainJPanel;
        this.scheduleOfAllCrops=scheduleOfAllCrops;
        cropPlannerScheduleList = new ArrayList<>();
        this.person = person;
        this.cropPlannerList = cropPlannerList;
        cropPlanner = getCropPlannerObject();
        this.MainJPanel = MainJPanel;
        selectedCrops = this.cropPlanner.getSelectedCropsList();
        
        // After login, need to get name and username of crop planner from login component and add to crop
        // planner object here
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        buttonLayout = new javax.swing.JPanel();
        forecaseBtn = new javax.swing.JButton();
        cropPlantingBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        logoutBtn = new javax.swing.JButton();
        workAreaJPanel = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setOpaque(false);

        jSplitPane1.setBackground(new java.awt.Color(255, 255, 255));
        jSplitPane1.setOpaque(false);

        buttonLayout.setBackground(new java.awt.Color(255, 255, 255));
        buttonLayout.setOpaque(false);

        forecaseBtn.setText("Analyse And Forecast");
        forecaseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                forecaseBtnActionPerformed(evt);
            }
        });

        cropPlantingBtn.setText("Crop Planting Schedule");
        cropPlantingBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cropPlantingBtnActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(204, 255, 255));
        jLabel1.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\deepa\\OneDrive\\Desktop\\welcome.png")); // NOI18N
        jLabel1.setText("Welcome Crop Planner");
        jLabel1.setOpaque(true);

        logoutBtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\deepa\\OneDrive\\Desktop\\cross.png")); // NOI18N
        logoutBtn.setText("Logout");
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout buttonLayoutLayout = new javax.swing.GroupLayout(buttonLayout);
        buttonLayout.setLayout(buttonLayoutLayout);
        buttonLayoutLayout.setHorizontalGroup(
            buttonLayoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonLayoutLayout.createSequentialGroup()
                .addGroup(buttonLayoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(buttonLayoutLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(buttonLayoutLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(buttonLayoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cropPlantingBtn)
                            .addComponent(forecaseBtn)
                            .addComponent(logoutBtn))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        buttonLayoutLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cropPlantingBtn, forecaseBtn, logoutBtn});

        buttonLayoutLayout.setVerticalGroup(
            buttonLayoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonLayoutLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81)
                .addComponent(forecaseBtn)
                .addGap(28, 28, 28)
                .addComponent(cropPlantingBtn)
                .addGap(34, 34, 34)
                .addComponent(logoutBtn)
                .addContainerGap(109, Short.MAX_VALUE))
        );

        buttonLayoutLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {cropPlantingBtn, forecaseBtn, logoutBtn});

        jSplitPane1.setLeftComponent(buttonLayout);

        workAreaJPanel.setBackground(new java.awt.Color(255, 255, 255));
        workAreaJPanel.setOpaque(false);
        workAreaJPanel.setLayout(new java.awt.CardLayout());
        jSplitPane1.setRightComponent(workAreaJPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        // TODO add your handling code here:
        MainJPanel.remove(this);
        CardLayout layout = (CardLayout) MainJPanel.getLayout();
        layout.previous(MainJPanel);
    }//GEN-LAST:event_logoutBtnActionPerformed

    public CropPlanner getCropPlannerObject(){
        for (CropPlanner planner : cropPlannerList) {
            if(planner.getUserName().equalsIgnoreCase(person.getUserName())){
                return planner;
            }
        }
        return null;
    }
    

   
    private void forecaseBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_forecaseBtnActionPerformed
        // TODO add your handling code here:

        CPAnalyseForecastDemandJPanel analysePanel = new CPAnalyseForecastDemandJPanel(workAreaJPanel,
                selectedCrops);
        workAreaJPanel.add("analysePanel", analysePanel);

        CardLayout layout = (CardLayout) workAreaJPanel.getLayout();
        layout.next(workAreaJPanel);
    }// GEN-LAST:event_forecaseBtnActionPerformed

    private void cropPlantingBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_cropPlantingBtnActionPerformed
        // TODO add your handling code here:

        CropPlantingScheduleJPanel cropPlantingScheduleJPanel = new CropPlantingScheduleJPanel(workAreaJPanel,
                cropPlanner, scheduleOfAllCrops, selectedCrops);
        workAreaJPanel.add("cropPlantingScheduleJPanel", cropPlantingScheduleJPanel);

        CardLayout layout = (CardLayout) workAreaJPanel.getLayout();
        layout.next(workAreaJPanel);
    }// GEN-LAST:event_cropPlantingBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonLayout;
    private javax.swing.JButton cropPlantingBtn;
    private javax.swing.JButton forecaseBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JPanel workAreaJPanel;
    // End of variables declaration//GEN-END:variables
}
