/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.RoleBasedWorkAreas;

import Business.LoginPerson.LoginPerson;
import Business.Roles.DataAnalyst;
import Business.Roles.DeliveryDriver;
import Business.Roles.WarehouseCoordinator;
import UserInterface.RoleBasedWorkAreas.WareHouseCoordinator.PlanDeliveriesJPanel;
import java.awt.CardLayout;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JPanel;

/**
 *
 * @author yash
 */
public class WarehouseCoordinatorJPanel extends javax.swing.JPanel {

    /**
     * Creates new form WarehouseCoordinatorJPanel
     */
    LoginPerson person;
    List<WarehouseCoordinator> warehouseCoordinatorList;
    JPanel MainJPanel;
    WarehouseCoordinator loggedIn;
    List<DeliveryDriver> deliveryDriverListAll;

    public WarehouseCoordinatorJPanel(
            LoginPerson person,
            List<WarehouseCoordinator> warehouseCoordinatorList,
            JPanel MainJPanel, List<DeliveryDriver> deliveryDriverList) {
        this.MainJPanel = MainJPanel;
        this.person = person;
        this.warehouseCoordinatorList = warehouseCoordinatorList;
        this.deliveryDriverListAll = deliveryDriverList;
        loggedIn = getWHC();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        buttonJPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnPlanDeliveries = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        workAreaJPanel = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setOpaque(false);

        jSplitPane1.setBackground(new java.awt.Color(255, 255, 255));
        jSplitPane1.setOpaque(false);

        buttonJPanel.setBackground(new java.awt.Color(255, 255, 255));
        buttonJPanel.setOpaque(false);

        jLabel1.setBackground(new java.awt.Color(204, 255, 255));
        jLabel1.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\deepa\\OneDrive\\Desktop\\welcome.png")); // NOI18N
        jLabel1.setText("Welcome  Coordinator !");
        jLabel1.setOpaque(true);

        btnPlanDeliveries.setText("Plan Deliveries");
        btnPlanDeliveries.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlanDeliveriesActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\deepa\\OneDrive\\Desktop\\cross.png")); // NOI18N
        jButton2.setText("Logout");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout buttonJPanelLayout = new javax.swing.GroupLayout(buttonJPanel);
        buttonJPanel.setLayout(buttonJPanelLayout);
        buttonJPanelLayout.setHorizontalGroup(
            buttonJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(buttonJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btnPlanDeliveries)
                    .addComponent(jButton2)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        buttonJPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnPlanDeliveries, jButton2, jLabel1});

        buttonJPanelLayout.setVerticalGroup(
            buttonJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonJPanelLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addComponent(btnPlanDeliveries)
                .addGap(74, 74, 74)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        buttonJPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnPlanDeliveries, jButton2});

        jSplitPane1.setLeftComponent(buttonJPanel);

        workAreaJPanel.setBackground(new java.awt.Color(255, 255, 255));
        workAreaJPanel.setOpaque(false);
        workAreaJPanel.setLayout(new java.awt.CardLayout());
        jSplitPane1.setRightComponent(workAreaJPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 912, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jSplitPane1)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    public WarehouseCoordinator getWHC() {
        for (WarehouseCoordinator whc : warehouseCoordinatorList) {
            if (whc.getUserName().equalsIgnoreCase(person.getUserName())) {
                return whc;
            }
        }
        return null;
    }
    private void btnPlanDeliveriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlanDeliveriesActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout) workAreaJPanel.getLayout();
        PlanDeliveriesJPanel planDeliveriesJPanel = new PlanDeliveriesJPanel(deliveryDriverListAll);
        workAreaJPanel.add("planDeliveriesJPanel", planDeliveriesJPanel);
        layout.next(workAreaJPanel);
    }//GEN-LAST:event_btnPlanDeliveriesActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        MainJPanel.remove(this);
        CardLayout layout = (CardLayout) MainJPanel.getLayout();
        layout.previous(MainJPanel);
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPlanDeliveries;
    private javax.swing.JPanel buttonJPanel;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JPanel workAreaJPanel;
    // End of variables declaration//GEN-END:variables
}
